#!/usr/bin/env python3
"""
Installer Generator for OBS QR Donations Plugin

This script creates platform-specific installers for the plugin.
Supported platforms: Windows, macOS, Linux
"""
import os
import sys
import shutil
import platform
import subprocess
from pathlib import Path
from datetime import datetime

# Configuration
VERSION = "1.0.0"
PLUGIN_NAME = "obs-qr-donations"
OBS_PLUGIN_DIRS = {
    "Windows": os.path.expandvars(r"%APPDATA%\\obs-studio\\plugins"),
    "Darwin": os.path.expanduser("~/Library/Application Support/obs-studio/plugins"),
    "Linux": os.path.expanduser("~/.config/obs-studio/plugins")
}

class Installer:
    def __init__(self):
        self.platform = platform.system()
        self.build_dir = Path("build")
        self.dist_dir = Path("dist")
        self.plugin_dir = self.build_dir / PLUGIN_NAME
        
        # Create necessary directories
        self.build_dir.mkdir(exist_ok=True)
        self.dist_dir.mkdir(exist_ok=True)
        
    def clean_build(self):
        """Clean the build directory."""
        if self.plugin_dir.exists():
            shutil.rmtree(self.plugin_dir)
        
    def copy_plugin_files(self):
        """Copy plugin files to build directory."""
        print("Copying plugin files...")
        
        # Create plugin directory structure
        (self.plugin_dir / "bin").mkdir(parents=True, exist_ok=True)
        (self.plugin_dir / "data").mkdir(exist_ok=True)
        
        # Copy plugin files
        shutil.copytree("resources", self.plugin_dir / "resources", dirs_exist_ok=True)
        
        # Platform-specific files
        if self.platform == "Windows":
            shutil.copy("build/Release/obs-qr-donations.dll", self.plugin_dir / "bin/")
        elif self.platform == "Darwin":
            shutil.copy("build/obs-qr-donations.so", self.plugin_dir / "bin/")
        else:  # Linux
            shutil.copy("build/obs-qr-donations.so", self.plugin_dir / "bin/")
        
        # Copy data files
        shutil.copy("README.md", self.plugin_dir / "README.txt")
        shutil.copy("LICENSE", self.plugin_dir / "LICENSE.txt")
    
    def create_windows_installer(self):
        """Create a Windows installer using Inno Setup."""
        print("Creating Windows installer...")
        
        # Create NSIS script
        nsis_script = f"""
        ; Script generated by OBS QR Donations Installer Generator
        Name "OBS QR Donations Plugin"
        OutFile "{str(self.dist_dir / f'{PLUGIN_NAME}-{VERSION}-windows.exe')}"
        InstallDir "$APPDATA\\obs-studio\\plugins\\{PLUGIN_NAME}"
        
        Section "Install"
            SetOutPath "$INSTDIR"
            File /r "{self.plugin_dir}\\*"
        SectionEnd
        """
        
        script_path = self.build_dir / "installer.nsi"
        with open(script_path, 'w') as f:
            f.write(nsis_script)
        
        # Run NSIS compiler if available
        try:
            subprocess.run(["makensis", str(script_path)], check=True)
            print(f"Installer created: {self.dist_dir / f'{PLUGIN_NAME}-{VERSION}-windows.exe'}")
        except FileNotFoundError:
            print("NSIS not found. Please install NSIS to create Windows installers.")
    
    def create_macos_installer(self):
        """Create a macOS package."""
        print("Creating macOS package...")
        pkg_path = self.dist_dir / f"{PLUGIN_NAME}-{VERSION}-macos.pkg"
        
        # Create package using pkgbuild
        try:
            subprocess.run([
                "pkgbuild",
                "--identifier", "com.obsproject.plugin.qr-donations",
                "--version", VERSION,
                "--install-location", "/Library/Application Support/obs-studio/plugins/qr-donations",
                "--root", str(self.plugin_dir),
                str(pkg_path)
            ], check=True)
            print(f"Package created: {pkg_path}")
        except subprocess.CalledProcessError as e:
            print(f"Failed to create macOS package: {e}")
    
    def create_linux_installer(self):
        """Create a Linux package."""
        print("Creating Linux package...")
        
        # Create DEB package
        deb_dir = self.build_dir / "deb"
        deb_plugin_dir = deb_dir / f"usr/share/obs/obs-plugins/{PLUGIN_NAME}"
        deb_plugin_dir.mkdir(parents=True, exist_ok=True)
        
        # Copy files
        shutil.copytree(self.plugin_dir, deb_plugin_dir, dirs_exist_ok=True)
        
        # Create control file
        control_file = deb_dir / "DEBIAN/control"
        control_file.parent.mkdir(exist_ok=True)
        
        with open(control_file, 'w') as f:
            f.write(f"""
            Package: obs-qr-donations
            Version: {VERSION}
            Section: video
            Priority: optional
            Architecture: amd64
            Maintainer: Your Name <your.email@example.com>
            Description: OBS Studio plugin for receiving cryptocurrency donations
                         This plugin adds QR code donation functionality to OBS Studio.
            """)
        
        # Build package
        try:
            subprocess.run([
                "dpkg-deb", "--build", str(deb_dir),
                str(self.dist_dir / f"{PLUGIN_NAME}-{VERSION}-linux.deb")
            ], check=True)
            print(f"Package created: {self.dist_dir / f'{PLUGIN_NAME}-{VERSION}-linux.deb'}")
        except subprocess.CalledProcessError as e:
            print(f"Failed to create DEB package: {e}")
    
    def create_installer(self):
        """Create installer for the current platform."""
        self.clean_build()
        self.copy_plugin_files()
        
        if self.platform == "Windows":
            self.create_windows_installer()
        elif self.platform == "Darwin":
            self.create_macos_installer()
        else:  # Linux
            self.create_linux_installer()

def main():
    print(f"Creating installer for {platform.system()}...")
    
    installer = Installer()
    installer.create_installer()
    
    print("\nInstallation complete!")
    print(f"Installers are available in: {installer.dist_dir.absolute()}")

if __name__ == "__main__":
    main()
